QA Workshop Project/Code/Demo.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.BLL.Repositry;
using Demo.DAL.Models;
using Demo.PL.Helpers;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using static System.Net.Mime.MediaTypeNames;

namespace Demo.PL.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        
        //private readonly IEmployeeRepositry _employeeRepositry;
        //private readonly IDepartmentRepositry _departmentRepositry;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<Employee> _unitOfWork;

        public EmployeeController(/*IEmployeeRepositry employeeRepositry, IDepartmentRepositry departmentRepositry, IMapper mapper*/ IUnitOfWork<Employee> unitOfWork,IMapper mapper )
        {
            //_employeeRepositry = employeeRepositry;
            //_departmentRepositry = departmentRepositry;
            _mapper = mapper;
           _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult>Index(string SearchValue) 
        {
            // Binding is one way 
            // View Date => send info from action to view [Binding] ( first way =>Dictionary object )
            //ViewData["Message"] = "Hello from View Data";

            //ViewBag=>No diffrence till now [Dynamic property as Dynamic Featuere ]
            //ViewBag.Message = "Hello from View Bag";

            IEnumerable<Employee> employees;
            if (string.IsNullOrEmpty(SearchValue))

                employees =await _unitOfWork.EmployeeRepositry.getAll();
            else

                employees = _unitOfWork.EmployeeRepositry.SerachEmployeeByName(SearchValue);

            var mappedEmp = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);

            return View(mappedEmp);

        }
        [HttpGet]
        public IActionResult Create()
        {
            //ViewBag.Departments = _departmentRepositry.getAll();

            return View();
        }
        [HttpPost]
        public  async Task <IActionResult> Create(EmployeeViewModel employeeVM)
        {
            if (ModelState.IsValid)
            //Manual Mapping
            {
                ///    var employee =new Employee()
                ///    {
                ///        Name=employeeVM.Name,
                ///        Address=employeeVM.Address,
                ///        EmailAddress=employeeVM.EmailAddress,
                ///        Salary=employeeVM.Salary,   
                ///        Age=employeeVM.Age,
                ///        DepartmentId=employeeVM.DepartmentId,   
                ///        IsActive=employeeVM.IsActive,
                ///        HireDate=employeeVM.HireDate,
                ///        Phone=employeeVM.Phone, 
                ///    };

                employeeVM.ImageName= DocumentSettings.UploadFile(employeeVM.Image, "Images");

                var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);

               await _unitOfWork.EmployeeRepositry.Add(mappedEmp);

                //Updte
                //Delete

               await  _unitOfWork.Complete();
                
                


                return RedirectToAction(nameof(Index));
            }
            return View(employeeVM);

        }
        public async Task <IActionResult> Details(int? id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();//400
            var employee =await _unitOfWork.EmployeeRepositry.get(id.Value);



            if (employee is null)
                return NotFound();
            var mappedEmp = _mapper.Map<Employee, EmployeeViewModel>(employee);

            return View(ViewName, mappedEmp);
        }
        [HttpGet]
        public async Task <IActionResult> Edit(int? id)
        {
            //if (id is null)
            //    return BadRequest();//400
            //var department = _departmentRepositry.get(id.Value);

            //if (department is null)
            //    return NotFound();

            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> Edit([FromRoute] int id, EmployeeViewModel employeeVM)
        {
            if (id != employeeVM.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                    _unitOfWork.EmployeeRepositry.Update(mappedEmp);
                  await  _unitOfWork.Complete();

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(employeeVM);
        }

        public async  Task <IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> Delete([FromRoute] int id, EmployeeViewModel employeeVM)
        {
            try
            {
                var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                _unitOfWork.EmployeeRepositry.Delete(mappedEmp);
               int count= await _unitOfWork.Complete();

                if (count > 0)
                    DocumentSettings.DeleteFile(employeeVM.ImageName, "Images");

                
                
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View(employeeVM);
        }

    }
}

QA Workshop Project/Code/Demo.PL/Controllers/RoleController.cs
using Demo.DAL.Models;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using AutoMapper;

namespace Demo.PL.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IMapper _mapper;

        public RoleController(RoleManager<IdentityRole> roleManager, IMapper mapper)
        {
            _roleManager = roleManager;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                var roles = await _roleManager.Roles.Select(R => new RoleViewModel()
                {
                    Id = R.Id,

                    RoleName = R.Name
                }).ToListAsync();
                return View(roles);
            }
            else
            {

                var role = await _roleManager.FindByNameAsync(name);

                if(role is not null)
                {

                    var mappRole = new RoleViewModel()
                    {
                        Id = role.Id,
                        RoleName = role.Name


                    };
                    return View(new List<RoleViewModel>() { mappRole });

                }
                return View(Enumerable.Empty<RoleViewModel>());
            }


        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task < IActionResult>Create(RoleViewModel roleVM)

        {
            if (ModelState.IsValid)
            {
                var mappedRole= _mapper.Map<RoleViewModel ,IdentityRole>(roleVM);
                await _roleManager.CreateAsync(mappedRole); 
                
                return RedirectToAction(nameof(Index));
            }
            return View(roleVM);
        }


        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();//400
            var role = await _roleManager.FindByIdAsync(id);



            if (role is null)
                return NotFound();
            var mappedRole = _mapper.Map<IdentityRole, RoleViewModel>(role);

            return View(ViewName, mappedRole);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            //if (id is null)
            //    return BadRequest();//400
            //var department = _departmentRepositry.get(id.Value);

            //if (department is null)
            //    return NotFound();

            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, RoleViewModel UpdatedRole)
        {
            if (id != UpdatedRole.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(id);
                    role.Name = UpdatedRole.RoleName;
                    
                    
                    await _roleManager.UpdateAsync(role);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(UpdatedRole);
        }


        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete(string id, RoleViewModel deletedRole)
        {
            if (id != deletedRole.Id)
                return BadRequest();

            try
            {

                var role = await _roleManager.FindByIdAsync(id);


                //user.SecurityStamp = Guid.NewGuid().ToString();
                await _roleManager.DeleteAsync(role);


                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return RedirectToAction("Error", "Home");
        }


    }


}

QA Workshop Project/Code/Demo.PL/Controllers/UserController.cs
using AutoMapper;
using Demo.DAL.Models;
using Demo.PL.Helpers;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IMapper _mapper;

        public UserController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IMapper mapper)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(string email)
        {
            if (string.IsNullOrEmpty(email))
            {
                var Users = await _userManager.Users.Select(U => new UserViewModel()
                {
                    Id = U.Id,
                    FName = U.FName,
                    LName = U.LName,
                    PhoneNumber = U.PhoneNumber,
                    Email = U.Email,
                    Roles = _userManager.GetRolesAsync(U).Result
                }).ToListAsync();
                return View(Users);
            }
            else
            {
                var user = await _userManager.FindByEmailAsync(email);

                var mappUser = new UserViewModel()
                {
                    Id = user.Id,
                    FName = user.FName,
                    LName = user.LName,
                    PhoneNumber = user.PhoneNumber,
                    Email = user.Email,
                    Roles = _userManager.GetRolesAsync(user).Result
                };
                return View(new List<UserViewModel>() { mappUser });
            }


        }

        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();//400
            var user = await _userManager.FindByIdAsync(id);



            if (user is null)
                return NotFound();
            var mappedUser = _mapper.Map<ApplicationUser, UserViewModel>(user);

            return View(ViewName, mappedUser);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            //if (id is null)
            //    return BadRequest();//400
            //var department = _departmentRepositry.get(id.Value);

            //if (department is null)
            //    return NotFound();

            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, UserViewModel UpdatedUser)
        {
            if (id != UpdatedUser.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var user=await _userManager.FindByIdAsync(id);
                    user.FName = UpdatedUser.FName;
                    user.LName = UpdatedUser.LName; 
                    user.PhoneNumber = UpdatedUser.PhoneNumber; 
                    user.Email = UpdatedUser.Email;

                    user.SecurityStamp=Guid.NewGuid().ToString();
                    await _userManager.UpdateAsync(user);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(UpdatedUser);
        }


        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete( string id, UserViewModel deletedUser)
        {
            if (id != deletedUser.Id)
                return BadRequest();

            try
            {

                var user = await _userManager.FindByIdAsync(id);
               

                //user.SecurityStamp = Guid.NewGuid().ToString();
                await _userManager.DeleteAsync(user);


                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return RedirectToAction("Error","Home");
        }



    }
}

QA Workshop Project/Code/Demo.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib

Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Login Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/authLayoutt.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->



	<link href="img/favicon.ico" rel="icon">

	<!-- Google Web Fonts -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

	<!-- Icon Font Stylesheet -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

	<!-- Libraries Stylesheet -->
	<link href="lib/animate/animate.min.css" rel="stylesheet">
	<link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

	<!-- Customized Bootstrap Stylesheet -->
	<link href="css/bootstrap.min.css" rel="stylesheet">

	<!-- Template Stylesheet -->
	<link href="css/style.css" rel="stylesheet">





</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1> @ViewData["Title"] Form</h1>
		@RenderBody();
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>Learning Hub || <a href="https://colorlib.com/" target="_blank">All Rights Reserved &cap;</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	
	@await RenderSectionAsync("ValidationScriptSection", required: false)


</body>
</html>

QA Workshop Project/Code/Demo.PL/Views/Shared/_ButtonsPartialView.cshtml
@model string 

<td> <a  asp-action="Details" class="btn btn-warning" asp-route-id="@Model"><i class="fas fa-eye"></i>Details</a> </td>
<td><a  asp-action="Edit" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-edit"></i>Update</a></td>
<td><a  asp-action="Delete" class="btn btn-danger" asp-route-id="@Model"><i class="fas fa-trash"></i>Delete</a></td>

QA Workshop Project/Code/Demo.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
   
    
*@
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/animate/animate.min.css" rel="stylesheet">
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="css/site.css" rel="stylesheet">
   
</head>

<body>
 
  
        <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
            <a href="index.html" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
             
            <h2 class="m-0 text-primary" style="color: #28a745;">Learning HUB</h2>

            </a>
            <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto p-4 p-lg-0">

@*                <a class="nav-item nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
*@
                 <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">User Main Pages</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a asp-action="Index"  class="dropdown-item">History</a>
                        <li class="nav-item">
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Privacy">Languages</a>
                        </li>
                    
                    </div>
                </div>
                <a href="#" class="nav-item nav-link">
                    <i class="bi bi-bell"></i> <!-- Example icon using Bootstrap Icons -->
                </a>
                <a class="nav-item nav-link" asp-area="" asp-controller="Account" asp-action="SignOut">Sign out </a>

            </div>
             </div>
        </nav>





@*
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>



                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark btn btn-light " asp-area="" asp-controller="User" asp-action="Index">Users </a>
                        </li>



                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark btn btn-light " asp-area="" asp-controller="Role" asp-action="Index">Roles </a>
                        </li>


                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark btn btn-light " asp-area="" asp-controller="Account" asp-action="SignOut">Sign out </a>
                        </li>

                        

                    </ul>
                </div>
            </div>
        </nav>
    </header>
*@




    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  @*  <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>